<div class="container" style="margin-top:10px;">
	<div class="jumbotron">
		<p>SCG Test function</p>
		<p>This is my first time PHP framework </p>
		<p>I didn't use cache function, because I don't know how to use it. (Sorry)</p>
		<br>
		<p><a class="btn btn-primary btn-lg" href="<?=$this->url('home');?>test/<?=$this->lang;?>/func1/4/" role="button"><?=$this->translate('First Function');?></a></p>
		<p><a class="btn btn-primary btn-lg" href="<?=$this->url('home');?>test/<?=$this->lang;?>/func2/" role="button"><?=$this->translate('Second Function');?></a></p>
		<p><?=$this->result;?></p>
		<p>Result is : <?=$this->value;?></p>
	</div>
</div>